### DISCUSSION TITLE
How do I write a custom `avr-hal` for atmega32u4 devices?

### DISCUSSION THREAD

**Discussion by mainrs** [Rahix/avr-hal#337] [Q&A] [answered]
I am trying to write a hal for the arduboy. Since the device uses an atmega32u4, I wanted to base my implementation on the arduino uno crate.

But it seems that `atmega-hal` is not published. Is there any way to use the crate?

**Comment by Rahix** [comment, marked as answer]
Yeah, unfortunately we haven't published to crates.io yet (#59).  In the meantime, you can just use a git-dependency on `atmega-hal` like this:

```toml
[dependencies.atmega-hal]
git = "https://github.com/rahix/avr-hal"
rev = "4cbb163deddac1651ce3374c8d91dbe7b7bb63ff"
features = ["rt", "atmega32u4"]
```
