### DISCUSSION TITLE
nano/atmega328p: programmer is not responding

### DISCUSSION THREAD

**Discussion by jngls** [Rahix/avr-hal#375] [Q&A] [answered]
I'm currently unable to upload to my arduino nano (atmega328p).

The error is:
```
avrdude.exe: stk500_recv(): programmer is not responding
avrdude.exe: stk500_getsync() attempt 1 of 10: not in sync: resp=0xdf
```

My ravedude runner is:
```toml
[target.'cfg(target_arch = "avr")']
runner = "ravedude -cb 57600 -P com4 nano"
```

I have been able to upload manually using:
```bat
avr-objcopy -O ihex ./target/avr-atmega328p/release/thing.elf ./target/avr-atmega328p/release/thing.hex
avrdude -F -c arduino -p m328p -P com4 -U flash:w:./target/avr-atmega328p/release/thing.hex
```
Note, I was unable to use `-c avrisp`, and instead had to use `-c arduino` here, so I'm wondering if ravedude is selecting the wrong programmer for my board?

Any ideas?
