### DISCUSSION TITLE
get more free space from SRAM

### DISCUSSION THREAD

**Discussion by djdisodo** [Rahix/avr-hal#463] [General]
```toml
[unstable]
build-std-features = ["panic_immediate_abort"]
```

add this to project `.cargo/config.toml` this will strip out most of the error messages from sram

remove when you want to see panic messages
