### DISCUSSION TITLE
getting embassy run and time-keeping

### DISCUSSION THREAD

**Discussion by djdisodo** [Rahix/avr-hal#464] [General]
[embassy_time driver for avr](https://github.com/djdisodo/avr_tc0_embassy_time)
[example](https://github.com/djdisodo/avr_tc0_embassy_time)
[patch for embassy](https://github.com/djdisodo/embassy)

![image](https://github.com/Rahix/avr-hal/assets/17721656/437d4592-24c7-49e0-96a5-2cf25044784a)

**Comment by djdisodo** [comment]
here's new version of the driver [repo](https://github.com/djdisodo/avr_embassy_time)

this supports higher resolution for both Instants and scheduling

it uses TC1 instead

![image](https://github.com/Rahix/avr-hal/assets/17721656/ce9f4b38-427a-4186-8307-4dc0f4962e6e)

example code driving stepper motor

i found it 0.5ms step to be unstable not recommended

this code can run at the same time while other async code running

set source clock by changing feature on embassy_time_drvier
for example 16MHz(which uno uses)

```toml
[dependencies]
embassy-time-driver = { version = "0.1.0", features = ["tick-hz-16_000_000"]}
```

set prescalar with feature
```toml
[dependencies.avr_tc1_embassy_time]
path = "../avr_embassy_time"
default-features = false
features = ["prescalar64"]
```

embassy_time is very lightweight and you can use it even without embassy

so i'll recommend to use this crate even if you won't use async code
