### DISCUSSION TITLE
Basic configs for getting started

### DISCUSSION THREAD

**Discussion by Vilayat-Ali** [Rahix/avr-hal#466] [Q&A] [answered]
I am a newbie to arduino environment and I'm using a Neo 6m GPS module for an Arduino-based robotics project. 

I generated a new avr-hal template project and programmed code to listen to serial port and console the bytes received but at my VSCode, the console is configured for a different baudrate meanwhile I need 9600 baudrate to conceive signals in a meaningful way.

Right now I'm stuck using Arduino IDE to read consoles for serial port 0 and 1 (RX and TX serial ports)

![image](https://github.com/Rahix/avr-hal/assets/73014428/9f1cf76a-24f2-4730-9cbc-7cd82c73aa35)

**Comment by Rahix** [comment, marked as answer]
If I understand your problem correctly, the solution is to change the baudrate in `.cargo/config.toml`:

```toml
[target.'cfg(target_arch = "avr")']
runner = "ravedude uno -cb 57600"
#                          ^- change the baudrate here
```
