### DISCUSSION TITLE
embassy+ufmt+usart: unexpected outputs?

### DISCUSSION THREAD

**Discussion by brainstorm** [Rahix/avr-hal#530] [Q&A] [answered]
I'm confused with the Usart+ufmt behavior on my Atmega2560, see this output in the commit message: https://github.com/brainstorm/embassy-as5600/commit/a37b9b5dbd582d673abf9a00ef8a9e6864a45b07

Probably an embassy main task related issue since it should print just one line but seems to print garbage in a loop instead? 

The baudrate seems **fixed to 115200 everywhere** (flashing (in .cargo/config.toml with ravedude) and running via `cargo run`)... it also looks like a baudrate mismatch issue but I cannot see where the different baudrate setting can come from? Here's my [`.cargo/config.toml`](https://github.com/brainstorm/embassy-as5600/blob/a37b9b5dbd582d673abf9a00ef8a9e6864a45b07/.cargo/config.toml):

```toml
[build]
target = "avr-specs/avr-atmega328p.json"

[target.'cfg(target_arch = "avr")']
runner = "ravedude mega2560 -cb 115200"

[unstable]
build-std = ["core"]
```

My experience looks very similar to https://github.com/Rahix/avr-hal/discussions/466, but my baudrates seem [consistent and set to `115200` in the code itself too](https://github.com/brainstorm/embassy-as5600/blob/a37b9b5dbd582d673abf9a00ef8a9e6864a45b07/src/main.rs#L16)?

/cc @djdisodo
