### ISSUE TITLE
how to create a new board crate outside of avr-hal?

### ISSUE THREAD

**Issue by MarkuBu** [Rahix/avr-hal#123]
Hi, I want to create a new board, but outside of the avr-hal crate. How can I do this?

Regards

**Comment by Rahix** [comment]
I think the easiest way is to copy an existing board crate directory and adjust all the necessary bits in `Cargo.toml`.  For example:

```toml
[dependencies.atmega328p-hal]
git = "https://github.com/Rahix/avr-hal.git"
rev = "<latest git commit hash from avr-hal>"
features = ["atmega328p"]

[dependencies.avr-hal-generic]
git = "https://github.com/Rahix/avr-hal.git"
rev = "<latest git commit hash from avr-hal>"
```

**Comment by Rahix** [comment]
You'll also want to include the target json file for your MCU, e.g. `avr-specs/avr-atmega328p.json`.  You'll then need to adjust the path to it in `.cargo/config.toml`.

**Comment by MarkuBu** [comment]
Thanks for the quick response. I don't know how to adjust the path to the target JSON file. At least I don't know how to set the correct path in Windows

**Comment by Rahix** [comment]
Let's say your new board crate is in the `my-board/` directory.  I.e. there is a `my-board/Cargo.toml` for the crate.  Copy `avr-specs/avr-atmega328p.json` into this directory, so `my-board/avr-atmega328p.json`.  Then put the following in `my-board/.cargo/config.toml`:

```toml
[build]
target = "avr-atmega328p.json"

[unstable]
build-std = ["core"]
```
