### ISSUE TITLE
Unable to use avr-hal-generic as a dependency

### ISSUE THREAD

**Issue by tjf801** [Rahix/avr-hal#282]
I am trying to use `avr_hal_generic` as a dependency, due to wanting to implement a struct like this:
```rust
struct SevenSegmentDisplay<D, S, C>
 where D: avr_hal_generic::port::PinOps,
       S: avr_hal_generic::port::PinOps,
       C: avr_hal_generic::port::PinOps 
{
    serial_data: Pin<mode::Output, D>,
    shift_register_clock: Pin<mode::Output, S>,
    storage_register_clock: Pin<mode::Output, C>,
}
```
and I've tried the solution given in #98 to no avail, as it seems like there are actually two implementations of `PinOps`, one from each different dependency. Here's the full compiler output and Cargo.toml if they help at all.

```
   Compiling arduino-uno-rust v0.1.0 (C:\Users\REDACTED\Desktop\programming_2022\arduino-uno-rust)
error[E0599]: the method `set_low` exists for struct `avr_hal_generic::port::Pin<arduino_hal::port::mode::Output, C>`, but its trait bounds were not satisfied
   --> src\main.rs:138:37
    |
138 |         self.storage_register_clock.set_low();
    |                                     ^^^^^^^ method cannot be called on `avr_hal_generic::port::Pin<arduino_hal::port::mode::Output, C>` due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `C: avr_hal_generic::port::PinOps`

error[E0277]: the trait bound `PB0: PinOps` is not satisfied
   --> src\main.rs:179:35
    |
179 |                     let display = SevenSegmentDisplay {
    |                                   ^^^^^^^^^^^^^^^^^^^ the trait `PinOps` is not implemented for `PB0`
    |
note: required by a bound in `SevenSegmentDisplay`
   --> src\main.rs:101:11
    |
100 | struct SevenSegmentDisplay<D, S, C>
    |        ------------------- required by a bound in this
101 |  where D: avr_hal_generic::port::PinOps,
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `SevenSegmentDisplay`

error[E0277]: the trait bound `PB2: PinOps` is not satisfied
   --> src\main.rs:179:35
    |
179 |                     let display = SevenSegmentDisplay {
    |                                   ^^^^^^^^^^^^^^^^^^^ the trait `PinOps` is not implemented for `PB2`
    |
note: required by a bound in `SevenSegmentDisplay`
   --> src\main.rs:102:11
    |
100 | struct SevenSegmentDisplay<D, S, C>
    |        ------------------- required by a bound in this
101 |  where D: avr_hal_generic::port::PinOps,
102 |        S: avr_hal_generic::port::PinOps,
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `SevenSegmentDisplay`

error[E0277]: the trait bound `PB1: PinOps` is not satisfied
   --> src\main.rs:179:35
    |
179 |                     let display = SevenSegmentDisplay {
    |                                   ^^^^^^^^^^^^^^^^^^^ the trait `PinOps` is not implemented for `PB1`
    |
note: required by a bound in `SevenSegmentDisplay`
   --> src\main.rs:103:11
    |
100 | struct SevenSegmentDisplay<D, S, C>
    |        ------------------- required by a bound in this
...
103 |        C: avr_hal_generic::port::PinOps
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `SevenSegmentDisplay`

error[E0599]: the method `display_hex_digit` exists for struct `SevenSegmentDisplay<PB0, PB2, PB1>`, but its trait bounds were not satisfied        
   --> src\main.rs:185:29
    |
100 | / struct SevenSegmentDisplay<D, S, C>
101 | |  where D: avr_hal_generic::port::PinOps,
102 | |        S: avr_hal_generic::port::PinOps,
103 | |        C: avr_hal_generic::port::PinOps
...   |
107 | |     storage_register_clock: Pin<mode::Output, C>,
108 | | }
    | |_- method `display_hex_digit` not found for this
...
185 |                       display.display_hex_digit(x);
    |                               ^^^^^^^^^^^^^^^^^ method cannot be called on `SevenSegmentDisplay<PB0, PB2, PB1>` due to unsatisfied trait bounds
    |
   ::: C:\Users\REDACTED\.cargo\git\checkouts\avr-hal-f3855d5807fdfd57\d0d2f24\mcu\atmega-hal\src\port.rs:2:1
    |
2   | / avr_hal_generic::impl_port_traditional! {
3   | |     enum Ports {
4   | |         PORTB: (crate::pac::PORTB, portb, pinb, ddrb),
5   | |         PORTC: (crate::pac::PORTC, portc, pinc, ddrc),
...   |
33  | |     }
34  | | }
    | | -
    | | |
    | | doesn't satisfy `PB0: PinOps`
    | |_doesn't satisfy `PB1: PinOps`
    |   doesn't satisfy `PB2: PinOps`
    |
    = note: the following trait bounds were not satisfied:
            `PB0: PinOps`
            `PB2: PinOps`
            `PB1: PinOps`

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `arduino-uno-rust` due to 5 previous errors
```

Cargo.toml:
```toml
[package]
name = "arduino-uno-rust"
version = "0.1.0"
authors = ["tjf801"]
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "arduino-uno-rust"
test = false
bench = false

[dependencies]
panic-halt = "0.2.0"
ufmt = "0.1.0"
nb = "0.1.2"
embedded-hal = "0.2.3"
avr-device = "0.3.3"

[dependencies.arduino-hal]
git = "https://github.com/rahix/avr-hal"
rev = "d0d2f243bd3e10b49f6a78d44839a6caa8be7d43"
features = ["arduino-uno"]

[dependencies.avr-hal-generic]
git = "https://github.com/Rahix/avr-hal"

# Configure the build for minimal size - AVRs have very little program memory
[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"
```

Addendum: I am honestly quite new to rust, so there is a large chance I am just doing something wrong here but I can't for the life of me figure out what it is
