### ISSUE TITLE
Re-export prelude of / whole crate `avr-hal-generic` in `mcu/*-hal` crates

### ISSUE THREAD

**Issue by icanwalkonwater** [Rahix/avr-hal#332]
### Why ?

Currently, when working with the crates of this repository, doing anything more than a blinky requires adding a bunch of dependencies that are already present in the upstream crates, just hidden.

For example, in a very basic app that uses only the serial and logs panics to it, I need all of these:
```toml
[dependencies]
# For interrupt::disable
avr-device = { version = "0.3", features = ["atmega1284p"] }
# For the uart hal
atmega-hal = { git = "https://github.com/icanwalkonwater/avr-hal.git", features = ["rt", "atmega1284p"] }
# For its prelude (uWrite + void)
avr-hal-generic = { git = "https://github.com/icanwalkonwater/avr-hal.git" }
# For uwriteln!
ufmt = "0.2"
```

Each one of these crates is already in the dependency tree of `atmega-hal` and is thus prone to version conflicts. The goal of this issue is to propose a solution for this.

### Reexport `avr-hal-generic`'s prelude

The prelude of `avr-hal-generic` currently reexports traits from `embedded-hal`, `ufmt` and `void`, which are compiled either way and are useful to have in downstream crates.

The proposal is to create a prelude for the `mcu/*-hal` which reexports `avr-hal-generic::prelude::*`.
Something like
```rust
// mcu/atmega-hal/src/lib.rs

pub mod prelude {
    pub use avr-hal-generic::prelude::*;
}
```
And maybe the same things in further downstream crates like `arduino-hal`.

This will also prevent version conflicts related issues as well. #303 #282

### Reexport `avr-hal-generic`

In addition to that, reexporting the whole `avr-hal-generic` crates will be great, this was discarded as useless #98 but I'd argue that this is a similar case to the `pac` reexport in mcu crates and the `hal` one in `arduino-hal`, it allows users to drop down a level (or up in this case) and get access to all the traits and reexports of this crate to write more generic code.

This is similar to what they do on the `stm32-rs` project, for example in [`stm32f3xx-hal`](https://docs.rs/stm32f3xx-hal/0.9.0/stm32f3xx_hal/), the `nb` crate traits are implemented a bit everywhere and reexported at the root.
