### ISSUE TITLE
how do i add the avr generic hal crate

### ISSUE THREAD

**Issue by XxMicrowavexX** [Rahix/avr-hal#648]

**Comment by Rahix** [comment]
Please at least put in the effort to write a proper description of what problem you are having and what you already attempted.  Otherwise others won't put in the effort to answer.

I assume, from what little info you provided, that you need this:

```toml
[dependencies.avr-hal-generic]
git = "https://github.com/rahix/avr-hal"
rev = "3c089795cadbbc7fa83f45958128689fee7ba1e4"
```
